# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Zip all pipelines
        run: |
          RELEASE_DIR="releases"
          pipelines=$(ls -l |grep dcsazure_ | awk '{print $NF}')
          for pipeline in ${pipelines}; do 
              zip ${pipeline}.zip ${pipeline}
          done 

          mkdir -vp $RELEASE_DIR
          mv *.zip $RELEASE_DIR/ 
          zip -r artifacts.zip $RELEASE_DIR/

      - name: Create Release 
        uses: actions/create-release@v1 
        id: create_release 
        with:
          draft: false
          prerelease: false 
          release_name: "Release ${{ github.ref }}"
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts.zip 
          asset_name: dcsforazure-pipeline.zip
          asset_content_type: application/zip 
        
          
